version: '3'

services:
  user-db:
    image: mongo:4.2
    hostname: user-mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - user-volume:/data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - 3005:3005
    environment:
      ME_CONFIG_MONGODB_SERVER: user-mongo-db
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      VCAP_APP_PORT: 3005
    depends_on:
      - user-db

volumes:
  user-volume:
    driver: local