FROM golang:1.13-alpine as builder

RUN apk update && apk add --no-cache git gcc libc-dev
RUN go get -u github.com/golang/dep/cmd/dep
COPY ./src/api ./src/api
WORKDIR /go/src/api
RUN dep ensure
RUN go install
CMD /wait && /go/bin/api