version: '3'

services:
  user-db:
    image: mongo:4.2
    container_name: user-mongo-db
    hostname: user-mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - user-volume:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - 3005:3005
    environment:
      ME_CONFIG_MONGODB_SERVER: user-mongo-db
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      VCAP_APP_PORT: 3005
    depends_on:
      - user-db

  mongo-go:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    image: gusugusu1018/mongogo/api:dev
    container_name: mongo-go
    ports:
      - 3006:3006
    restart: always
    environment:
      MONGODB_URL: mongodb://user-mongo-db:27017
      MONGODB_ADMIN_NAME: root
      MONGODB_ADMIN_PASS: example
      WAIT_HOSTS: user-mongo-db:27017
      GIN_MODE: debug
      PORT: 3006
    depends_on:
      - user-db

volumes:
  user-volume:
    driver: local
