version: '3'

services:
  user-db:
    image: mongo:4.2
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - user-volume:/data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - 3005:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - user-db
    links:
      - user-db:mongo

  mongo-go:
    build:
      context: ./
      dockerfile: Dockerfile-dev
    image: gusugusu1018/mongogo/api:dev
    environment:
      MONGODB_URL: mongodb://user-db:27017
      MONGODB_ADMIN_NAME: root
      MONGODB_ADMIN_PASS: example
      WAIT_HOSTS: user-db:27017
      GIN_MODE: debug
      PORT: 3006
    depends_on:
      - user-db
    links:
      - user-db:mongo

volumes:
  user-volume:
    driver: local
