version: '3'

services:
  user-db:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - user-volume:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 3002:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - user-db

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: gusugusu1018/mongogo/api:latest
    restart: always
    environment:
      MONGODB_URL: mongodb://user-db:27017/user
      MONGODB_ADMIN_NAME: root
      MONGODB_ADMIN_PASS: example
      WAIT_HOSTS: user-db:27017
    depends_on:
      - user-db

volumes:
  user-volume:
    driver: local
