FROM golang:1.13-alpine as builder

RUN apk update && apk add --no-cache git gcc libc-dev
RUN go get -u github.com/golang/dep/cmd/dep
COPY ./src/api ./src/api
WORKDIR /go/src/api
RUN dep ensure
RUN go install

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.5.0/wait /wait
RUN chmod +x /wait

#CMD /wait && /go/bin/api
CMD /bin/ash