version: '3'

services:
  user-db:
    image: mongo:4.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - user-volume:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 3005:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    depends_on:
      - user-db
    links:
      - user-db:mongo

volumes:
  user-volume:
    driver: local